import {
	threeDObjectImg,
	audioImg,
	calculatorImg,
	chromeImg,
	notesImg,
	pcImg,
	settingsImg,
	terminalImg,
	textEditorImg,
	trashEmptyImg,
	videoImg,
	vscodeImg,
	youtubeImg,
	zorinImg,
} from '../assets/images/apps';

export const APP_LIST = [
	{ title: 'My Computer', name: 'pc', icon: pcImg },
	{ title: 'Audio', name: 'audio', icon: audioImg },
	{ title: 'Calculator', name: 'calculator', icon: calculatorImg },
	{ title: 'Chrome', name: 'chrome', icon: chromeImg },
	{ title: 'Notes', name: 'notes', icon: notesImg },
	{ title: 'Settings', name: 'settings', icon: settingsImg },
	{ title: 'Terminal', name: 'terminal', icon: terminalImg },
	{ title: 'Notepad', name: 'notepad', icon: textEditorImg },
	{ title: 'Trash', name: 'trash', icon: trashEmptyImg },
	{ title: 'Video', name: 'video', icon: videoImg },
	{ title: 'Vscode', name: 'vscode', icon: vscodeImg },
	{ title: 'Youtube', name: 'youtube', icon: youtubeImg },
	{ title: 'Zorin', name: 'zorin', icon: zorinImg },
	{ title: '3d Object', name: '3d_object', icon: threeDObjectImg },
];
